blank_issues_enabled: false
contact_links:
  - name: Question
    url: https://github.com/whiteducksoftware/cloud-control-community/discussions
    about: Please ask your questions in the Discussions tab
