name: Feature request
description: Suggest an idea for this project
title: "Short precise title of your feature request"
labels: ["enhancement", "triage"]
assignees: 
  - ndeeH
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: dropdown
    id: plan
    attributes:
      label: Plan
      description: What plan of our build agent are you running?
      options:
        - Single Windows VM Plan
        - Linux VM Scale Set Plan
    validations:        
      required: true
  - type: textarea
    attributes:
      label: Problem
      description: Is your feature request related to a problem?
    validations:
      required: false
  - type: textarea
    attributes:
      label: Expected Behavior
      description: Describe the solution you'd like
      placeholder: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Alternative Behavoir
      description: Describe alternatives you've considered
      placeholder: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional context
      description: |
        Links? References? Anything that will give us more context about the feature request here.

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
